version: '3.8'

services:
  backend:
    build:
      context: ./rt_backend_services
    ports:
      - "5000:5000"

  web:
    build:
      context: ./rt_web_services
    ports:
      - "3000:3000"
    depends_on:
      - backend