# Use official Python image
FROM python:3.11-slim

WORKDIR /app

COPY app.py /app
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3000


CMD ["python", "app.py", "--port=3000"]
